### ISSUE TITLE
E4GL30S1NT Error

### ISSUE THREAD

**Issue by Kitopvibe1** [C0MPL3XDEV/E4GL30S1NT#12]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/E4GL30S1NT", line 48, in <module>
    configs = json.loads(open("configs/config.json", "r").read())
FileNotFoundError: [Errno 2] No such file or directory: 'configs/config.json'

![Screenshot_20220901-124236](https://user-images.githubusercontent.com/110231650/187905892-a66ef172-8bd8-47d6-88a6-07cde0526200.jpg)

**Comment by Enn3Developer** [comment]
Not the author, just an outsider (the author seems to have abandoned answering the issues)
did you run the script from the folder where `configs/` is contained?

**Comment by Yfgig** [comment]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/E4GL30S1NT", line 14, in <module>
    from lxml.html import fromstring
ModuleNotFoundError: No module named 'lxml'
![Screenshot_2023-10-04-20-27-59-71_84d3000e3f4017145260f7618db1d683](https://github.com/C0MPL3XDEV/E4GL30S1NT/assets/93402265/da502fe5-fe4c-4137-bce3-e91e49df6468)

**Comment by C0MPL3XDEV** [comment]
Both errors reported here have been fixed in [v2.0.5](https://github.com/C0MPL3XDEV/E4GL30S1NT/releases/tag/v2.0.5):

- **`FileNotFoundError: configs/config.json`** — the config is now handled properly by the package regardless of where you run the command from.
- **`ModuleNotFoundError: No module named 'lxml'`** — `lxml` is now listed as an explicit dependency and gets installed automatically.

Make sure to reinstall after updating:
```bash
pip install -e .
```
or, if you're on Termux:
```bash
pip install eagleosint --upgrade
```

Feel free to reopen if you're still seeing issues after upgrading!
